
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: final            # build only up to the final/runtime stage
      args:
        NODE_VERSION: ${NODE_VERSION:-24.8.0}
    image: sveltekit-app:latest
    env_file:
      - .env                   # optional .env file (place NODE_ENV, PORT, etc. here)
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3000}
    ports:
      - "${PORT:-3000}:3000"
    restart: unless-stopped
    labels:
      <<: *default-labels
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Optionally enable a lightweight healthcheck — note: uses wget/curl inside container.
    # If your runtime image doesn't include wget/curl, either install it in the image or
    # remove/comment the healthcheck below.
    #healthcheck:
    #  test: ["CMD-SHELL", "wget -qO- --timeout=2 http://localhost:${PORT:-3000}/ || exit 1"]
    #  interval: 30s
    #  timeout: 5s
    #  retries: 3
    #  start_period: 10s

# Optional extra services (db, cache) can be added below, with appropriate depends_on
# volumes: (none required for runtime by default)
